import type { POI, RouteTheme } from "./types";

/** 首尔圣水洞种子 POI 数据 */
export const SEONGSU_SEED_DATA: POI[] = [
  // ── 买衣服 / 古着 ──
  {
    id: "seongsu-001",
    name: "Ader Error 圣水旗舰店",
    nameKo: "아더에러 성수 플래그십",
    category: "shop",
    subcategory: "买衣服",
    lat: 37.5445,
    lng: 127.0559,
    address: "首尔城东区圣水洞2街 289-14",
    subwayExit: "4号口",
    walkingMinutes: 3,
    popularity: 92,
    description: "韩国顶级设计师品牌旗舰店，建筑本身就是打卡点",
  },
  {
    id: "seongsu-002",
    name: "Beaker 圣水",
    nameKo: "비이커 성수",
    category: "shop",
    subcategory: "买衣服",
    lat: 37.5451,
    lng: 127.0564,
    address: "首尔城东区圣水洞2街 300-22",
    subwayExit: "4号口",
    walkingMinutes: 3,
    popularity: 85,
    description: "集合买手店，韩系设计师品牌精选",
  },
  {
    id: "seongsu-003",
    name: "Rockfish Weatherwear 圣水",
    nameKo: "락피쉬웨더웨어 성수",
    category: "shop",
    subcategory: "买衣服",
    lat: 37.5448,
    lng: 127.0568,
    address: "首尔城东区圣水洞2街 300-48",
    subwayExit: "4号口",
    walkingMinutes: 5,
    popularity: 78,
    description: "韩国人气雨靴&户外品牌，英伦复古风",
  },
  {
    id: "seongsu-004",
    name: "Empty 圣水",
    nameKo: "엠티 성수",
    category: "vintage",
    subcategory: "买衣服",
    lat: 37.5455,
    lng: 127.0552,
    address: "首尔城东区圣水洞2街 289-55",
    subwayExit: "4号口",
    walkingMinutes: 2,
    popularity: 88,
    description: "超大规模买手店，每一层不同风格",
  },
  {
    id: "seongsu-005",
    name: "Raive 圣水",
    nameKo: "라이브 성수",
    category: "vintage",
    subcategory: "买衣服",
    lat: 37.5460,
    lng: 127.0558,
    address: "首尔城东区圣水洞2街 291-12",
    subwayExit: "4号口",
    walkingMinutes: 4,
    popularity: 72,
    description: "暗黑风设计师品牌集合，Balenciaga爱好者必去",
  },
  {
    id: "seongsu-006",
    name: "低俗小说 Vintage",
    nameKo: "펄프픽션 빈티지",
    category: "vintage",
    subcategory: "买衣服",
    lat: 37.5442,
    lng: 127.0572,
    address: "首尔城东区圣水洞2街 297-33",
    subwayExit: "4号口",
    walkingMinutes: 7,
    popularity: 65,
    description: "隐藏在小巷里的美式古着店，衬衫和牛仔很出彩",
  },

  // ── 咖啡 / 甜品 ──
  {
    id: "seongsu-007",
    name: "Camel Coffee 圣水",
    nameKo: "카멜커피 성수",
    category: "cafe",
    subcategory: "咖啡",
    lat: 37.5449,
    lng: 127.0560,
    address: "首尔城东区圣水洞2街 300-8",
    subwayExit: "4号口",
    walkingMinutes: 3,
    popularity: 90,
    description: "红砖工业风咖啡馆，招牌拿铁+可露丽",
  },
  {
    id: "seongsu-008",
    name: "Aellista 圣水",
    nameKo: "아엘리사 성수",
    category: "cafe",
    subcategory: "咖啡",
    lat: 37.5458,
    lng: 127.0548,
    address: "首尔城东区圣水洞2街 285-5",
    subwayExit: "3号口",
    walkingMinutes: 2,
    popularity: 75,
    description: "极简纯白咖啡厅，适合拍照，提拉米苏很出名",
  },
  {
    id: "seongsu-009",
    name: "Paraspara 圣水",
    nameKo: "파라스파라 성수",
    category: "cafe",
    subcategory: "咖啡",
    lat: 37.5453,
    lng: 127.0566,
    address: "首尔城东区圣水洞2街 299-10",
    subwayExit: "4号口",
    walkingMinutes: 5,
    popularity: 82,
    description: "如画廊般的咖啡馆，季节性手冲单品",
  },
  {
    id: "seongsu-010",
    name: "Donghae Dakang 圣水",
    nameKo: "동해다방 성수",
    category: "cafe",
    subcategory: "咖啡",
    lat: 37.5436,
    lng: 127.0554,
    address: "首尔城东区圣水洞2街 305-28",
    subwayExit: "4号口",
    walkingMinutes: 8,
    popularity: 68,
    description: "老式茶馆改造，红豆冰和传统韩菓一绝",
  },

  // ── 餐厅 / 吃东西 ──
  {
    id: "seongsu-011",
    name: "圣水阁楼",
    nameKo: "성수다락",
    category: "restaurant",
    subcategory: "吃东西",
    lat: 37.5456,
    lng: 127.0562,
    address: "首尔城东区圣水洞2街 293-8",
    subwayExit: "4号口",
    walkingMinutes: 4,
    popularity: 87,
    description: "韩牛烤肉+创意韩食，工业风装修，需要预约",
  },
  {
    id: "seongsu-012",
    name: "Tsukemen Iroha 圣水",
    nameKo: "츠케멘 이로하 성수",
    category: "restaurant",
    subcategory: "吃东西",
    lat: 37.5444,
    lng: 127.0566,
    address: "首尔城东区圣水洞2街 298-15",
    subwayExit: "4号口",
    walkingMinutes: 6,
    popularity: 70,
    description: "日本蘸面专门店，汤底浓郁，排队但值得",
  },
  {
    id: "seongsu-013",
    name: "圣水洞脊骨汤",
    nameKo: "성수동감자탕",
    category: "restaurant",
    subcategory: "吃东西",
    lat: 37.5439,
    lng: 127.0570,
    address: "首尔城东区圣水洞2街 301-7",
    subwayExit: "4号口",
    walkingMinutes: 8,
    popularity: 60,
    description: "本地人常去的土豆排骨汤，便宜大碗",
  },
  {
    id: "seongsu-014",
    name: "Mona 圣水",
    nameKo: "모나 성수",
    category: "restaurant",
    subcategory: "吃东西",
    lat: 37.5450,
    lng: 127.0555,
    address: "首尔城东区圣水洞2街 295-22",
    subwayExit: "4号口",
    walkingMinutes: 2,
    popularity: 76,
    description: "韩国新锐主厨的融合料理，午餐套餐性价比高",
  },

  // ── 探店 / 文化 ──
  {
    id: "seongsu-015",
    name: "大林仓库画廊",
    nameKo: "대림창고 갤러리",
    category: "culture",
    subcategory: "探店",
    lat: 37.5437,
    lng: 127.0558,
    address: "首尔城东区圣水洞2街 303-11",
    subwayExit: "4号口",
    walkingMinutes: 6,
    popularity: 83,
    description: "旧仓库改造的当代艺术空间，展览质量很高",
  },
  {
    id: "seongsu-016",
    name: "圣水洞手工鞋街",
    nameKo: "성수동 수제화거리",
    category: "shop",
    subcategory: "探店",
    lat: 37.5446,
    lng: 127.0545,
    address: "首尔城东区圣水洞2街",
    subwayExit: "3号口",
    walkingMinutes: 2,
    popularity: 74,
    description: "韩国手工鞋作坊聚集地，可以定制属于自己的鞋子",
  },
  {
    id: "seongsu-017",
    name: "Seoul Upcycling Center",
    nameKo: "서울새활용플라자",
    category: "culture",
    subcategory: "探店",
    lat: 37.5462,
    lng: 127.0539,
    address: "首尔城东区圣水洞2街 283-44",
    subwayExit: "3号口",
    walkingMinutes: 5,
    popularity: 55,
    description: "可持续时尚概念空间，环保材料创意工坊",
  },
  {
    id: "seongsu-018",
    name: "圣水艺术空间",
    nameKo: "성수아트홀",
    category: "culture",
    subcategory: "探店",
    lat: 37.5453,
    lng: 127.0570,
    address: "首尔城东区圣水洞2街 296-4",
    subwayExit: "4号口",
    walkingMinutes: 6,
    popularity: 48,
    description: "独立艺术家展览+小型演出空间",
  },

  // ── 更多买衣服 ──
  {
    id: "seongsu-019",
    name: "Thisisneverthat 圣水",
    nameKo: "디스이즈네버댓 성수",
    category: "shop",
    subcategory: "买衣服",
    lat: 37.5452,
    lng: 127.0556,
    address: "首尔城东区圣水洞2街 292-18",
    subwayExit: "4号口",
    walkingMinutes: 3,
    popularity: 86,
    description: "韩国街头品牌代表，基础款品质极好",
  },
  {
    id: "seongsu-020",
    name: "Pandora Jeans",
    nameKo: "판도라진",
    category: "shop",
    subcategory: "买衣服",
    lat: 37.5457,
    lng: 127.0550,
    address: "首尔城东区圣水洞2街 287-9",
    subwayExit: "3号口",
    walkingMinutes: 2,
    popularity: 63,
    description: "韩国本土牛仔品牌，版型专为亚洲身材设计",
  },
  {
    id: "seongsu-021",
    name: "Gentle Monster 圣水",
    nameKo: "젠틀몬스터 성수",
    category: "shop",
    subcategory: "探店",
    lat: 37.5447,
    lng: 127.0563,
    address: "首尔城东区圣水洞2街 299-1",
    subwayExit: "4号口",
    walkingMinutes: 4,
    popularity: 95,
    description: "空间比眼镜更出名，每季换装置艺术展",
  },

  // ── 更多咖啡/甜点 ──
  {
    id: "seongsu-022",
    name: "Pie Republic 圣水",
    nameKo: "파이공화국 성수",
    category: "cafe",
    subcategory: "咖啡",
    lat: 37.5441,
    lng: 127.0569,
    address: "首尔城东区圣水洞2街 299-33",
    subwayExit: "4号口",
    walkingMinutes: 7,
    popularity: 58,
    description: "手工派专门店，伯爵茶味和苹果肉桂必点",
  },
  {
    id: "seongsu-023",
    name: "Hodu 圣水",
    nameKo: "호두 성수",
    category: "cafe",
    subcategory: "咖啡",
    lat: 37.5454,
    lng: 127.0546,
    address: "首尔城东区圣水洞2街 284-12",
    subwayExit: "3号口",
    walkingMinutes: 1,
    popularity: 71,
    description: "胡桃主题咖啡厅，坚果拿铁系列很特别",
  },
  {
    id: "seongsu-024",
    name: "Still Books",
    nameKo: "스틸북스",
    category: "cafe",
    subcategory: "探店",
    lat: 37.5456,
    lng: 127.0568,
    address: "首尔城东区圣水洞2街 294-5",
    subwayExit: "4号口",
    walkingMinutes: 5,
    popularity: 80,
    description: "独立杂志+咖啡复合空间，设计类书籍很全",
  },

  // ── 更多餐厅 ──
  {
    id: "seongsu-025",
    name: "圣水 Pasta Bar",
    nameKo: "성수파스타바",
    category: "restaurant",
    subcategory: "吃东西",
    lat: 37.5443,
    lng: 127.0556,
    address: "首尔城东区圣水洞2街 302-6",
    subwayExit: "4号口",
    walkingMinutes: 5,
    popularity: 64,
    description: "开放式厨房手工意面，氛围感满分",
  },
  {
    id: "seongsu-026",
    name: "Yang Good",
    nameKo: "양굿",
    category: "restaurant",
    subcategory: "吃东西",
    lat: 37.5459,
    lng: 127.0555,
    address: "首尔城东区圣水洞2街 290-3",
    subwayExit: "3号口",
    walkingMinutes: 3,
    popularity: 77,
    description: "新派韩式羊肉料理，清炖+烤制双吃",
  },
  {
    id: "seongsu-027",
    name: "圣水 Dduckbokki",
    nameKo: "성수떡볶이",
    category: "restaurant",
    subcategory: "吃东西",
    lat: 37.5438,
    lng: 127.0549,
    address: "首尔城东区圣水洞2街 307-2",
    subwayExit: "4号口",
    walkingMinutes: 8,
    popularity: 56,
    description: "超辣炒年糕+炸物拼盘，本地人最爱路边摊升级版",
  },

  // ── 更多探店 ──
  {
    id: "seongsu-028",
    name: "Daelim 创作工坊",
    nameKo: "대림창작공방",
    category: "culture",
    subcategory: "探店",
    lat: 37.5461,
    lng: 127.0542,
    address: "首尔城东区圣水洞2街 282-37",
    subwayExit: "3号口",
    walkingMinutes: 4,
    popularity: 45,
    description: "陶瓷+皮具+蜡烛手作体验，需要预约",
  },
  {
    id: "seongsu-029",
    name: "城东文化院",
    nameKo: "성동문화원",
    category: "culture",
    subcategory: "探店",
    lat: 37.5440,
    lng: 127.0543,
    address: "首尔城东区圣水洞1街 656-22",
    subwayExit: "3号口",
    walkingMinutes: 5,
    popularity: 40,
    description: "韩服体验+传统茶道，游客比较少的小众点",
  },
  {
    id: "seongsu-030",
    name: "Point of View 圣水",
    nameKo: "포인트오브뷰 성수",
    category: "shop",
    subcategory: "探店",
    lat: 37.5450,
    lng: 127.0567,
    address: "首尔城东区圣水洞2街 298-20",
    subwayExit: "4号口",
    walkingMinutes: 5,
    popularity: 89,
    description: "文具+生活方式选品店，韩国设计师文具集合",
  },
];

/** 按主题过滤 + 按热度排序 */
export function filterPoisByTheme(theme: RouteTheme, pois?: POI[]): POI[] {
  const source = pois ?? SEONGSU_SEED_DATA;
  return source
    .filter((p) => {
      switch (theme) {
        case "买衣服":
          return p.subcategory === "买衣服";
        case "吃东西":
          return p.subcategory === "吃东西";
        case "咖啡":
          return p.subcategory === "咖啡";
        case "探店":
          return p.subcategory === "探店" || p.category === "culture";
        case "文化":
          return p.category === "culture";
        case "综合":
        default:
          return true;
      }
    })
    .sort((a, b) => b.popularity - a.popularity);
}

/** 按名称查找 POI */
export function findPoiByName(name: string, pois?: POI[]): POI | undefined {
  const source = pois ?? SEONGSU_SEED_DATA;
  return source.find(
    (p) =>
      p.name === name ||
      p.nameKo === name ||
      p.name.includes(name) ||
      (p.nameKo && p.nameKo.includes(name)),
  );
}
